name: Tether
description: Privacy centric matrix client for everyone

# flutter commands
# $ flutter create --org org.tether tether
# $ flutter run --no-fast-start
# $ flutter pub global run devtools 
# $ flutter pub run build_runner build
# $ flutter pub run build_runner watch

# troubleshooting
# $ pub cache repair
# $ flutter pub cache repair

# mobile development commands
# $ xcrun simctl delete unavailable
# $ xcrun simctl list devices
# $ xcrun simctl boot <device-id>
# $ xcrun simctl boot 9EC4AC8E-5BD0-4D38-A8FC-52504C130844
# $ emulator -list-avds
# $ emulator -avd Pixel_3a_API_29

# desktop support options
# $ flutter config --enable-macos-desktop
# $ flutter config --no-enable-macos-desktop

# asset generation
# iOS icons - https://github.com/smallmuou/ios-icon-generator
#           - run generation script for ios and macos (desktop and mobile)
# android icons - use Android Studio with generic png

# env setup
# - defaults delete com.apple.dt.Xcode # Reset XCode settings
# - synctl start on 192.168.1.2 or respective local server
# - curl -XGET "http://192.168.1.2:8008/_matrix/client/r0/login" to test

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +. 
version: 0.0.7+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Domain / Store
  expandable: 3.0.1
  equatable: ^1.1.0
  crypt: ^3.0.0
  device_info: ^0.4.2
  redux: 4.0.0
  redux_thunk: 0.3.0
  redux_persist: 0.8.3
  redux_persist_flutter: 0.8.2
  flutter_redux: 0.6.0
  hive: ^1.3.0
  hive_flutter:  ^0.3.0
  flutter_secure_storage: 3.3.1+1 
  mime: ^0.9.6
  path_provider: 1.6.0  #https://github.com/flutter/plugins/pull/1570

  # Services
  http: 0.12.0+2
  html: ^0.13.3+3
  intl: ^0.16.1
  http_parser: 3.1.4
  flutter_dotenv: ^2.0.3
  android_alarm_manager: 0.4.5+8
  # workmanager: ^0.2.0

  # UI Only
  url_launcher: ^5.4.7
  flutter_svg: ^0.17.0
  image_picker: ^0.6.5
  flutter_swiper : 1.1.6
  webview_flutter: ^0.3.21
  touchable_opacity: 1.0.2  
  fab_circular_menu: ^1.0.0
  flutter_recaptcha_v2: 0.1.0
  smooth_page_indicator: 0.1.1
  flutter_local_notifications: 1.4.0
  flutter_material_color_picker: ^1.0.5
  # flutter_staggered_animations: "^0.1.2"

  # Desktop UI Only - UNCOMMENT FOR BUILDS
  # window_utils: 1.0.2

  # Converters
  dart_json_mapper: 1.3.3
  hive_generator: 0.7.0 
  # dart_json_mapper: ^1.5.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 400
        - asset: fonts/Rubik-Light.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # On release, change .env.debug to .env
  assets: 
   - .env.debug
   - .env.release
   - assets/graphics/undraw_sync_files.svg
   - assets/graphics/undraw_accept_terms.svg
   - assets/graphics/undraw_mobile_user.svg
   - assets/graphics/undraw_messaging_fun.svg
   - assets/graphics/undraw_connection.svg
   - assets/graphics/undraw_group_chat.svg
   - assets/graphics/undraw_people.svg
   - assets/graphics/undraw_site_content.svg
   - assets/graphics/undraw_escaping.svg

   - assets/graphics/undraw_in_thought.svg
   - assets/graphics/undraw_profile_data.svg
   - assets/graphics/undraw_mention.svg
   - assets/graphics/undraw_not_found.svg
   - assets/icons/tether_icon.svg
   - assets/icons/tether_icon.png
   - assets/icons/tether_icon_white.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
